-- =============================================
-- 装修管理模块
-- =============================================

CREATE TABLE IF NOT EXISTS t_decoration_application (
    fid VARCHAR(64) PRIMARY KEY COMMENT '申请ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    fowner_id VARCHAR(64) NOT NULL COMMENT '业主ID',
    fowner_name VARCHAR(50) NOT NULL COMMENT '业主姓名',
    fowner_phone VARCHAR(20) NOT NULL COMMENT '业主电话',
    froom_id VARCHAR(64) NOT NULL COMMENT '房间ID',
    fdecoration_type VARCHAR(20) NOT NULL COMMENT '装修类型',
    fdecoration_area DECIMAL(10,2) COMMENT '装修面积(㎡)',
    fdecoration_scope TEXT COMMENT '装修范围',
    fdecoration_content TEXT NOT NULL COMMENT '装修内容',
    fstart_date DATE NOT NULL COMMENT '计划开始日期',
    fend_date DATE NOT NULL COMMENT '计划结束日期',
    fconstruction_company VARCHAR(200) COMMENT '施工单位',
    fconstructor_name VARCHAR(50) COMMENT '施工负责人',
    fconstructor_phone VARCHAR(20) COMMENT '施工负责人电话',
    fworker_count INT DEFAULT 0 COMMENT '施工人数',
    fdeposit DECIMAL(10,2) DEFAULT 0 COMMENT '装修押金',
    fdeposit_paid INT DEFAULT 0 COMMENT '押金是否已缴',
    fdeposit_returned INT DEFAULT 0 COMMENT '押金是否已退',
    fdeposit_return_time DATETIME COMMENT '押金退还时间',
    fstatus VARCHAR(20) DEFAULT 'pending' COMMENT '状态',
    fapprover_id VARCHAR(64) COMMENT '审批人ID',
    fapprover_name VARCHAR(50) COMMENT '审批人姓名',
    fapprove_time DATETIME COMMENT '审批时间',
    fapprove_opinion TEXT COMMENT '审批意见',
    factual_start_date DATE COMMENT '实际开始日期',
    factual_end_date DATE COMMENT '实际结束日期',
    fdesign_urls TEXT COMMENT '设计图纸URLs(JSON数组)',
    flicense_urls TEXT COMMENT '施工资质URLs(JSON数组)',
    fother_urls TEXT COMMENT '其他附件URLs(JSON数组)',
    fremark TEXT COMMENT '备注',
    fcreate_user_id VARCHAR(64) COMMENT '创建人ID',
    fissue_date DATE COMMENT '开单日期',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id),
    INDEX idx_owner_id (fowner_id),
    INDEX idx_room_id (froom_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='装修申请表';

CREATE TABLE IF NOT EXISTS t_decoration_inspection (
    fid VARCHAR(64) PRIMARY KEY COMMENT '巡查ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    fapplication_id VARCHAR(64) NOT NULL COMMENT '装修申请ID',
    froom_id VARCHAR(64) NOT NULL COMMENT '房间ID',
    finspection_type VARCHAR(20) NOT NULL COMMENT '巡查类型',
    finspection_date DATE NOT NULL COMMENT '巡查日期',
    finspection_time DATETIME NOT NULL COMMENT '巡查时间',
    finspector_id VARCHAR(64) NOT NULL COMMENT '巡查人ID',
    finspector_name VARCHAR(50) COMMENT '巡查人姓名',
    fresult VARCHAR(20) DEFAULT 'normal' COMMENT '巡查结果',
    fissue_desc TEXT COMMENT '问题描述',
    frectify_requirement TEXT COMMENT '整改要求',
    frectify_deadline DATE COMMENT '整改期限',
    frectify_status VARCHAR(20) DEFAULT 'pending' COMMENT '整改状态',
    fverifier_id VARCHAR(64) COMMENT '验收人ID',
    fverifier_name VARCHAR(50) COMMENT '验收人姓名',
    fverify_time DATETIME COMMENT '验收时间',
    fverify_result TEXT COMMENT '验收结果',
    fphoto_urls TEXT COMMENT '现场照片URLs(JSON数组)',
    fvideo_urls TEXT COMMENT '现场视频URLs(JSON数组)',
    fremark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_application_id (fapplication_id),
    INDEX idx_room_id (froom_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='装修巡查表';

-- =============================================
-- 访客管理模块
-- =============================================

CREATE TABLE IF NOT EXISTS t_visitor (
    fid VARCHAR(64) PRIMARY KEY COMMENT '访客ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    fvisitor_name VARCHAR(50) NOT NULL COMMENT '访客姓名',
    fvisitor_phone VARCHAR(20) NOT NULL COMMENT '访客电话',
    fvisitor_id_card VARCHAR(18) COMMENT '访客身份证号',
    fvisitor_company VARCHAR(200) COMMENT '访客单位',
    fvisitor_count INT DEFAULT 1 COMMENT '访客人数',
    fowner_id VARCHAR(64) NOT NULL COMMENT '被访业主ID',
    fowner_name VARCHAR(50) NOT NULL COMMENT '被访人姓名',
    fowner_phone VARCHAR(20) NOT NULL COMMENT '被访人电话',
    froom_id VARCHAR(64) NOT NULL COMMENT '被访房间ID',
    fvisit_purpose VARCHAR(200) COMMENT '来访事由',
    fvisit_type VARCHAR(20) DEFAULT 'personal' COMMENT '访问类型',
    fis_appointment INT DEFAULT 0 COMMENT '是否预约',
    fappointment_time DATETIME COMMENT '预约时间',
    fentry_time DATETIME COMMENT '进入时间',
    fentry_gate VARCHAR(100) COMMENT '进入通道',
    fexit_time DATETIME COMMENT '离开时间',
    fexit_gate VARCHAR(100) COMMENT '离开通道',
    fstatus VARCHAR(20) DEFAULT 'invited' COMMENT '状态',
    fhas_vehicle INT DEFAULT 0 COMMENT '是否有车',
    fvehicle_no VARCHAR(20) COMMENT '车牌号',
    finvite_code VARCHAR(20) COMMENT '邀请码',
    finvite_expire_time DATETIME COMMENT '邀请码过期时间',
    fface_photo_url VARCHAR(500) COMMENT '人脸照片URL',
    fremark TEXT COMMENT '备注',
    fcreate_user_id VARCHAR(64) COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    UNIQUE KEY uk_invite_code (finvite_code),
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id),
    INDEX idx_owner_id (fowner_id),
    INDEX idx_room_id (froom_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='访客记录表';

CREATE TABLE IF NOT EXISTS t_visitor_blacklist (
    fid VARCHAR(64) PRIMARY KEY COMMENT '记录ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    fperson_name VARCHAR(50) NOT NULL COMMENT '人员姓名',
    fperson_phone VARCHAR(20) COMMENT '人员电话',
    fperson_id_card VARCHAR(18) COMMENT '身份证号',
    fperson_company VARCHAR(200) COMMENT '单位',
    fblacklist_reason VARCHAR(200) NOT NULL COMMENT '拉黑原因',
    fblacklist_desc TEXT COMMENT '详细说明',
    fblacklist_time DATETIME NOT NULL COMMENT '拉黑时间',
    funblacklist_time DATETIME COMMENT '解除时间',
    fstatus VARCHAR(20) DEFAULT 'active' COMMENT '状态',
    foperator_id VARCHAR(64) NOT NULL COMMENT '操作人ID',
    foperator_name VARCHAR(50) COMMENT '操作人姓名',
    fremark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id),
    INDEX idx_id_card (fperson_id_card)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='访客黑名单表';

-- =============================================
-- 品质管理模块
-- =============================================

CREATE TABLE IF NOT EXISTS t_inspection_task (
    fid VARCHAR(64) PRIMARY KEY COMMENT '任务ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    ftask_name VARCHAR(200) NOT NULL COMMENT '任务名称',
    ftask_code VARCHAR(50) COMMENT '任务编号',
    ftask_type VARCHAR(50) NOT NULL COMMENT '任务类型',
    fscope_type VARCHAR(20) DEFAULT 'project' COMMENT '范围类型',
    fscope_ids TEXT COMMENT '范围IDs(JSON数组)',
    fcheck_items TEXT NOT NULL COMMENT '检查项JSON数组',
    fcycle_type VARCHAR(20) DEFAULT 'daily' COMMENT '周期类型',
    fcycle_value INT DEFAULT 1 COMMENT '周期数值',
    fexecute_time VARCHAR(10) COMMENT '执行时间点',
    fexecutor_type VARCHAR(20) DEFAULT 'assign' COMMENT '执行人类型',
    fexecutor_ids TEXT COMMENT '执行人IDs(JSON数组)',
    fstart_date DATE NOT NULL COMMENT '开始日期',
    fend_date DATE COMMENT '结束日期',
    fstatus VARCHAR(20) DEFAULT 'active' COMMENT '状态',
    ftotal_count INT DEFAULT 0 COMMENT '总执行次数',
    fcompleted_count INT DEFAULT 0 COMMENT '完成次数',
    fpass_count INT DEFAULT 0 COMMENT '合格次数',
    fremark TEXT COMMENT '备注',
    fcreate_user_id VARCHAR(64) COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检任务表';

CREATE TABLE IF NOT EXISTS t_inspection_record (
    fid VARCHAR(64) PRIMARY KEY COMMENT '记录ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    ftask_id VARCHAR(64) COMMENT '任务ID',
    finspection_type VARCHAR(20) NOT NULL COMMENT '巡检类型',
    finspection_date DATE NOT NULL COMMENT '巡检日期',
    finspection_time DATETIME NOT NULL COMMENT '巡检时间',
    fbuilding_id VARCHAR(64) COMMENT '楼栋ID',
    funit_id VARCHAR(64) COMMENT '单元ID',
    farea_id VARCHAR(64) COMMENT '区域ID',
    flocation VARCHAR(200) COMMENT '巡检位置',
    finspector_id VARCHAR(64) NOT NULL COMMENT '巡检人ID',
    finspector_name VARCHAR(50) COMMENT '巡检人姓名',
    fresult VARCHAR(20) DEFAULT 'pass' COMMENT '结果',
    fscore DECIMAL(5,2) COMMENT '得分',
    ftotal_items INT DEFAULT 0 COMMENT '检查项总数',
    fpass_items INT DEFAULT 0 COMMENT '合格项数',
    ffail_items INT DEFAULT 0 COMMENT '不合格项数',
    fissue_count INT DEFAULT 0 COMMENT '问题数量',
    fissue_desc TEXT COMMENT '问题描述',
    frectify_status VARCHAR(20) DEFAULT 'none' COMMENT '整改状态',
    frectify_deadline DATE COMMENT '整改期限',
    frectify_time DATETIME COMMENT '整改时间',
    frectify_user_id VARCHAR(64) COMMENT '整改人ID',
    frectify_user_name VARCHAR(50) COMMENT '整改人姓名',
    fverify_time DATETIME COMMENT '验收时间',
    fverifier_id VARCHAR(64) COMMENT '验收人ID',
    fverifier_name VARCHAR(50) COMMENT '验收人姓名',
    fphoto_urls TEXT COMMENT '照片URLs(JSON数组)',
    fvideo_urls TEXT COMMENT '视频URLs(JSON数组)',
    fremark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id),
    INDEX idx_task_id (ftask_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检记录表';

CREATE TABLE IF NOT EXISTS t_pcar (
    fid VARCHAR(64) PRIMARY KEY COMMENT 'PCAR ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    finspection_id VARCHAR(64) NOT NULL COMMENT '巡检记录ID',
    fissue_no VARCHAR(50) NOT NULL COMMENT '问题编号',
    fissue_type VARCHAR(50) NOT NULL COMMENT '问题类型',
    fissue_level VARCHAR(20) DEFAULT 'normal' COMMENT '问题等级',
    fissue_desc TEXT NOT NULL COMMENT '问题描述',
    fissue_location VARCHAR(200) COMMENT '问题位置',
    fresponsibility_dept VARCHAR(100) COMMENT '责任部门',
    fresponsibility_user_id VARCHAR(64) COMMENT '责任人ID',
    fresponsibility_user_name VARCHAR(50) COMMENT '责任人姓名',
    frectify_requirement TEXT NOT NULL COMMENT '整改要求',
    frectify_deadline DATE NOT NULL COMMENT '整改期限',
    frectify_status VARCHAR(20) DEFAULT 'pending' COMMENT '整改状态',
    frectify_time DATETIME COMMENT '整改时间',
    frectify_user_id VARCHAR(64) COMMENT '整改人ID',
    frectify_user_name VARCHAR(50) COMMENT '整改人姓名',
    frectify_desc TEXT COMMENT '整改说明',
    fverify_status VARCHAR(20) DEFAULT 'pending' COMMENT '验收状态',
    fverify_time DATETIME COMMENT '验收时间',
    fverifier_id VARCHAR(64) COMMENT '验收人ID',
    fverifier_name VARCHAR(50) COMMENT '验收人姓名',
    fverify_opinion TEXT COMMENT '验收意见',
    fis_overdue INT DEFAULT 0 COMMENT '是否超期',
    foverdue_days INT DEFAULT 0 COMMENT '超期天数',
    foverdue_penalty DECIMAL(10,2) DEFAULT 0 COMMENT '超期扣款',
    fissue_photo_urls TEXT COMMENT '问题照片URLs(JSON数组)',
    frectify_photo_urls TEXT COMMENT '整改照片URLs(JSON数组)',
    fremark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id),
    INDEX idx_inspection_id (finspection_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='PCAR表';

-- =============================================
-- 安全管理模块
-- =============================================

CREATE TABLE IF NOT EXISTS t_safety_incident (
    fid VARCHAR(64) PRIMARY KEY COMMENT '事件ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    fincident_no VARCHAR(50) NOT NULL COMMENT '事件编号',
    fincident_name VARCHAR(200) NOT NULL COMMENT '事件名称',
    fincident_type VARCHAR(50) NOT NULL COMMENT '事件类型',
    fincident_level VARCHAR(20) DEFAULT 'minor' COMMENT '事件等级',
    foccur_time DATETIME NOT NULL COMMENT '发生时间',
    foccur_location VARCHAR(200) NOT NULL COMMENT '发生地点',
    fbuilding_id VARCHAR(64) COMMENT '楼栋ID',
    funit_id VARCHAR(64) COMMENT '单元ID',
    fincident_desc TEXT NOT NULL COMMENT '事件描述',
    fincident_cause TEXT COMMENT '事件原因',
    fdeath_count INT DEFAULT 0 COMMENT '死亡人数',
    finjury_count INT DEFAULT 0 COMMENT '受伤人数',
    fcasualty_desc TEXT COMMENT '伤亡情况描述',
    feconomic_loss DECIMAL(12,2) DEFAULT 0 COMMENT '经济损失(元)',
    fhandler_id VARCHAR(64) COMMENT '处理人ID',
    fhandler_name VARCHAR(50) COMMENT '处理人姓名',
    fhandle_time DATETIME COMMENT '处理时间',
    fhandle_desc TEXT COMMENT '处理过程',
    fstatus VARCHAR(20) DEFAULT 'processing' COMMENT '状态',
    fis_reported INT DEFAULT 0 COMMENT '是否上报',
    freport_time DATETIME COMMENT '上报时间',
    freport_dept VARCHAR(100) COMMENT '上报部门',
    fresponsibility_dept VARCHAR(100) COMMENT '责任部门',
    fresponsibility_user_id VARCHAR(64) COMMENT '责任人ID',
    fresponsibility_user_name VARCHAR(50) COMMENT '责任人姓名',
    fpenalty_desc TEXT COMMENT '处罚说明',
    fphoto_urls TEXT COMMENT '照片URLs(JSON数组)',
    fvideo_urls TEXT COMMENT '视频URLs(JSON数组)',
    fattachment_urls TEXT COMMENT '附件URLs(JSON数组)',
    fremark TEXT COMMENT '备注',
    fcreate_user_id VARCHAR(64) COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    UNIQUE KEY uk_incident_no (fincident_no),
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安全事件表';

CREATE TABLE IF NOT EXISTS t_safety_hazard (
    fid VARCHAR(64) PRIMARY KEY COMMENT '隐患ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) NOT NULL COMMENT '项目ID',
    fhazard_no VARCHAR(50) NOT NULL COMMENT '隐患编号',
    fhazard_name VARCHAR(200) NOT NULL COMMENT '隐患名称',
    fhazard_type VARCHAR(50) NOT NULL COMMENT '隐患类型',
    fhazard_level VARCHAR(20) DEFAULT 'minor' COMMENT '隐患等级',
    fdiscover_time DATETIME NOT NULL COMMENT '发现时间',
    fdiscover_location VARCHAR(200) NOT NULL COMMENT '隐患位置',
    fbuilding_id VARCHAR(64) COMMENT '楼栋ID',
    funit_id VARCHAR(64) COMMENT '单元ID',
    fhazard_desc TEXT NOT NULL COMMENT '隐患描述',
    fhazard_cause TEXT COMMENT '隐患原因',
    fdiscoverer_id VARCHAR(64) NOT NULL COMMENT '发现人ID',
    fdiscoverer_name VARCHAR(50) COMMENT '发现人姓名',
    frectify_requirement TEXT NOT NULL COMMENT '整改要求',
    frectify_deadline DATE NOT NULL COMMENT '整改期限',
    fresponsibility_dept VARCHAR(100) COMMENT '责任部门',
    fresponsibility_user_id VARCHAR(64) COMMENT '责任人ID',
    fresponsibility_user_name VARCHAR(50) COMMENT '责任人姓名',
    frectify_status VARCHAR(20) DEFAULT 'pending' COMMENT '整改状态',
    frectify_time DATETIME COMMENT '整改时间',
    frectify_user_id VARCHAR(64) COMMENT '整改人ID',
    frectify_user_name VARCHAR(50) COMMENT '整改人姓名',
    frectify_desc TEXT COMMENT '整改说明',
    fverify_status VARCHAR(20) DEFAULT 'pending' COMMENT '验收状态',
    fverify_time DATETIME COMMENT '验收时间',
    fverifier_id VARCHAR(64) COMMENT '验收人ID',
    fverifier_name VARCHAR(50) COMMENT '验收人姓名',
    fverify_opinion TEXT COMMENT '验收意见',
    fis_overdue INT DEFAULT 0 COMMENT '是否超期',
    foverdue_days INT DEFAULT 0 COMMENT '超期天数',
    fhazard_photo_urls TEXT COMMENT '隐患照片URLs(JSON数组)',
    frectify_photo_urls TEXT COMMENT '整改照片URLs(JSON数组)',
    fremark TEXT COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    UNIQUE KEY uk_hazard_no (fhazard_no),
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安全隐患表';

-- =============================================
-- 通知公告模块
-- =============================================

CREATE TABLE IF NOT EXISTS t_notice (
    fid VARCHAR(64) PRIMARY KEY COMMENT '公告ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) COMMENT '项目ID',
    ftitle VARCHAR(200) NOT NULL COMMENT '公告标题',
    fnotice_type VARCHAR(20) DEFAULT 'notice' COMMENT '类型',
    fimportance VARCHAR(20) DEFAULT 'normal' COMMENT '重要程度',
    fcontent TEXT NOT NULL COMMENT '公告内容',
    fsummary VARCHAR(500) COMMENT '摘要',
    faudience_type VARCHAR(20) DEFAULT 'all' COMMENT '受众类型',
    faudience_ids TEXT COMMENT '受众IDs(JSON数组)',
    fstatus VARCHAR(20) DEFAULT 'draft' COMMENT '状态',
    fpublish_time DATETIME COMMENT '发布时间',
    funpublish_time DATETIME COMMENT '撤回时间',
    feffective_start DATE COMMENT '生效开始日期',
    feffective_end DATE COMMENT '生效结束日期',
    fistop INT DEFAULT 0 COMMENT '是否置顶',
    ftop_end_time DATETIME COMMENT '置顶结束时间',
    fattachment_urls TEXT COMMENT '附件URLs(JSON数组)',
    fcover_url VARCHAR(500) COMMENT '封面图片URL',
    fread_count INT DEFAULT 0 COMMENT '阅读次数',
    flike_count INT DEFAULT 0 COMMENT '点赞次数',
    fpublisher_id VARCHAR(64) COMMENT '发布人ID',
    fpublisher_name VARCHAR(50) COMMENT '发布人姓名',
    fremark TEXT COMMENT '备注',
    fcreate_user_id VARCHAR(64) COMMENT '创建人ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_fec_id (fec_id),
    INDEX idx_project_id (fproject_id),
    INDEX idx_status (fstatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知公告表';

CREATE TABLE IF NOT EXISTS t_notice_read (
    fid VARCHAR(64) PRIMARY KEY COMMENT '记录ID(MD5)',
    fec_id VARCHAR(64) NOT NULL COMMENT '企业ID',
    fproject_id VARCHAR(64) COMMENT '项目ID',
    fnotice_id VARCHAR(64) NOT NULL COMMENT '公告ID',
    freader_id VARCHAR(64) NOT NULL COMMENT '阅读者ID',
    freader_name VARCHAR(50) COMMENT '阅读者姓名',
    freader_type VARCHAR(20) NOT NULL COMMENT '阅读者类型',
    fread_time DATETIME NOT NULL COMMENT '阅读时间',
    fdevice_type VARCHAR(20) COMMENT '设备类型',
    fdevice_info VARCHAR(200) COMMENT '设备信息',
    fliked INT DEFAULT 0 COMMENT '是否点赞',
    flike_time DATETIME COMMENT '点赞时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_time DATETIME,
    is_deleted INT DEFAULT 0,
    INDEX idx_notice_id (fnotice_id),
    INDEX idx_reader_id (freader_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='阅读记录表';

-- =============================================
-- 初始化数据
-- =============================================

-- 插入默认企业
INSERT INTO t_enterprise (fid, enterprise_name, enterprise_code, contact_person, contact_phone) VALUES
('ent_default_001', '粤海物业集团', 'YH001', '管理员', '13800138000');

-- 插入默认管理员用户 (密码: admin123)
INSERT INTO t_user (fid, username, password, real_name, phone, department, position, fec_id, fstatus) VALUES
('user_admin_001', 'admin', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.qVh.N9N9N9N9N9N', '系统管理员', '13800138000', '信息技术部', '管理员', 'ent_default_001', 'active');

-- 插入默认角色
INSERT INTO t_role (fid, role_name, role_code, description, fec_id) VALUES
('role_admin_001', '系统管理员', 'admin', '系统最高权限管理员', 'ent_default_001'),
('role_manager_001', '项目经理', 'manager', '项目管理员', 'ent_default_001'),
('role_staff_001', '普通员工', 'staff', '普通员工', 'ent_default_001');

-- 插入用户角色关联
INSERT INTO t_user_role (fid, fuser_id, frole_id, fec_id) VALUES
('ur_admin_001', 'user_admin_001', 'role_admin_001', 'ent_default_001');

-- 完成
SELECT '数据库初始化完成' AS message;