-- 员工表
CREATE TABLE IF NOT EXISTS t_pc_employee (
  FID varchar(32) NOT NULL DEFAULT '' COMMENT 'ID',
  FNumber varchar(50) DEFAULT NULL COMMENT '编码',
  FUserID varchar(32) DEFAULT NULL COMMENT '用户ID',
  FJob varchar(50) DEFAULT NULL COMMENT '工作岗位备注',
  FName varchar(50) DEFAULT NULL COMMENT '姓名',
  FPhone varchar(50) DEFAULT NULL COMMENT '手机',
  FEmail varchar(200) DEFAULT NULL COMMENT 'email',
  FECID varchar(32) DEFAULT NULL COMMENT '企业ID',
  FStatus tinyint DEFAULT 1 COMMENT '状态（0无效，1有效）',
  FCreator varchar(32) DEFAULT NULL COMMENT '创建人',
  FCreateTime datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  FUpdateTime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FHasJoinOrg tinyint DEFAULT NULL COMMENT '是否加入了金蝶云的组织',
  FAutoAuth tinyint DEFAULT NULL COMMENT '新增项目时自动授权',
  FDeleteTime datetime DEFAULT NULL COMMENT '删除时间',
  FUserUrl varchar(256) DEFAULT NULL COMMENT '用户头像',
  FIsDelete tinyint DEFAULT 0 COMMENT '是否删除（0否，1是）',
  FShowGuide tinyint DEFAULT 1 COMMENT '是否显示初始化引导',
  FJobTitle varchar(64) DEFAULT NULL COMMENT '工作岗位Title',
  FPerms varchar(64) DEFAULT NULL COMMENT '系统菜单权限',
  FEasID varchar(44) DEFAULT NULL,
  FIsOuter tinyint DEFAULT 0 COMMENT '外包人员',
  FBizType tinyint DEFAULT 11 COMMENT '业务类型',
  FSpell varchar(256) DEFAULT NULL COMMENT '用户名拼音',
  FOrgunitID varchar(1024) DEFAULT NULL COMMENT '所属组织',
  FOrgunitNames varchar(1024) DEFAULT NULL COMMENT '组织名称',
  FQuarterName varchar(120) DEFAULT NULL COMMENT '岗位名称',
  FQuarterID varchar(32) DEFAULT NULL COMMENT '岗位ID',
  FCertificateType varchar(32) DEFAULT NULL COMMENT '证件类型',
  FCertificateNumber varchar(1024) DEFAULT NULL COMMENT '证件号码',
  FSourceID varchar(64) DEFAULT NULL COMMENT '源ID',
  FDirectLeaderID varchar(32) DEFAULT NULL COMMENT '直接上级员工ID',
  FDirectLeaderName varchar(50) DEFAULT NULL COMMENT '直接上级员工名称',
  FSourceSystem varchar(64) DEFAULT NULL COMMENT '来源系统',
  FShowInsCancel tinyint(1) NOT NULL DEFAULT 2 COMMENT '是否显示仪表作废',
  FAuthCode varchar(50) DEFAULT NULL COMMENT '财务系统用户编码',
  FValidDate datetime DEFAULT NULL COMMENT '有效时间',
  FQwUserID varchar(64) DEFAULT NULL COMMENT '企业微信用户ID',
  FIsExternalStaff tinyint(1) DEFAULT 0 COMMENT '是否外部员工',
  FProviderID varchar(32) DEFAULT NULL COMMENT '外部员工关联供应商',
  PRIMARY KEY (FID),
  KEY Employee_EcID (FECID),
  KEY Employee_UserID (FUserID),
  KEY Employee_Number (FNumber)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工表';